# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date on which the badge was created.'),
        ),
    ]
