# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badges', '0002_auto_20170420_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='creator',
            field=models.ForeignKey(default=10, help_text='The user who created this badge.', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
