# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_badge_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='latitude',
            field=models.FloatField(default=0.0, help_text='The latitude at which the badge is located.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='longitude',
            field=models.FloatField(default=0.0, help_text='The longitude at which the badge is loacated.'),
            preserve_default=False,
        ),
    ]
